name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file ./deploy/Dockerfile --tag mukkematti/opentipp:latest
  publish_images:
    runs-on: ubuntu-latest
    steps:
    - name: Push to Docker Hub
      run: 
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}
        docker push mukkematti/opentipp:latest

